### ISSUE TITLE
Export in bash

### ISSUE THREAD

**Issue by noqcks** [adrienkohlbecker/ejson-kms#2]
Hey @adrienkohlbecker 

I noticed in 3.0.0 you removed the export from bash. https://github.com/adrienkohlbecker/ejson-kms/commit/655c3b0190b1b4c0c2eca1de731e6b328b664c39

This isn't necessarily an issue, but I was hoping you could give some guidance on the best way to use ejson-kms. 

We had planned to export decrypted secrets into the environment to be picked up by various applications. 

I was wondering how you are currently using ejson-kms if not exporting them in ENV variables? Or was this change just to remove export by default and exporting to ENV is acceptable usage?

Thank you for this great project!

**Comment by adrienkohlbecker** [comment]
Hi!

Exporting to environment is totally fine, but I removed the default export since you may want to use it differently, for example to pre-populate config files on disk before running a program:

```shell
#!/bin/bash

# this makes secrets accessible to the current script, but not to any programs called from that script
eval "$(ejson-kms export)"

# this works, you can populate config files for example
echo $MY_SECRET  > /etc/conffile

# doesn't have the secret in its env
printenv

# manually export it
export MY_SECRET

# now has the secret in its env
printenv
```

I hope this makes sense! Happy to hear feedback :-) 
Best
