### ISSUE TITLE
New GitHub release

### ISSUE THREAD

**Issue by noqcks** [adrienkohlbecker/ejson-kms#3]
Hi again @adrienkohlbecker! 

Could you make a new minor/patch release with [this](https://github.com/adrienkohlbecker/ejson-kms/commit/5db50b953244ca272f820749f5568381d686e471) commit in it? 

I'm using ejson-kms in my own cli and `dep init` grabs the latest release (3.0.0) which currently includes `adrienkohlbecker/errors` (private repo). 

Thanks

**Comment by adrienkohlbecker** [comment]
Done! https://github.com/adrienkohlbecker/ejson-kms/releases/tag/4.0.0

**Comment by noqcks** [comment]
Thank you! 👍
